// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresetApi.Data;

#nullable disable

namespace preset_api.Migrations
{
    [DbContext(typeof(PresetDbContext))]
    partial class PresetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PresetApi.Models.Preset", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Bpm")
                        .HasColumnType("int");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.PrimitiveCollection<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Presets");
                });

            modelBuilder.Entity("PresetApi.Models.Preset", b =>
                {
                    b.OwnsOne("PresetApi.Models.TimeSignature", "TimeSignature", b1 =>
                        {
                            b1.Property<string>("PresetId")
                                .HasColumnType("varchar(64)");

                            b1.Property<int>("Beats")
                                .HasColumnType("int");

                            b1.Property<int>("NoteValue")
                                .HasColumnType("int");

                            b1.HasKey("PresetId");

                            b1.ToTable("Presets");

                            b1.WithOwner()
                                .HasForeignKey("PresetId");
                        });

                    b.Navigation("TimeSignature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
