// Removes generated build output across the monorepo.
//
//   npm run clean            build output — fast, next build is fresh
//   npm run clean:all        the above plus Rust target dirs (tens of minutes)
//   npm run clean -- --dry-run   list what would go, delete nothing
//
// Deletes an explicit list of paths, never a glob. That matters here: the
// Android project under src-tauri/gen/ is generated by `tauri android init`
// BUT holds two hand-maintained files that exist in no commit —
// keystore.properties and the blocks appended to app/build.gradle.kts. Wiping
// gen/ wholesale costs you a signed build and a trip through desktop/README.md
// to restore them, so nothing here touches anything above a `build` directory.
//
// node_modules is dependencies, not output, and is left alone.

import { existsSync, rmSync, statSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '..');

const argv = process.argv.slice(2);
const dryRun = argv.includes('--dry-run');
const includeRust = argv.includes('--all');

// The default. Everything a build writes and then reads back — including
// Gradle's up-to-date cache, which has to go with its output: left behind, it
// can skip a task whose inputs look unchanged even though the toolchain around
// them moved. That is exactly how a stale unstripped .so survives a rebuild.
//
// Note what is NOT here: everything `tauri android init` generates lives one
// level up (app/build.gradle.kts, gradlew, app/src, keystore.properties) and is
// never touched, so cleaning never costs you a re-init.
const BUILD_OUTPUT = [
  'desktop/src-tauri/gen/android/app/build',
  'desktop/src-tauri/gen/android/build',
  'desktop/src-tauri/gen/android/.gradle',
  'desktop/tauri-plugin-google-drive-auth/android/build',
  'desktop/tauri-plugin-google-drive-auth/android/.gradle',
  'web/dist',
  'preset-api/bin',
  'preset-api/obj',
  'test/PresetApi.Tests/bin',
  'test/PresetApi.Tests/obj',
];

// Opt-in only (`--all`). Cargo's incremental state is reliable, so removing it
// buys correctness you almost never need while costing a rebuild of four
// Android ABIs plus the host — tens of minutes, and tens of gigabytes.
const RUST = [
  'desktop/src-tauri/target',
  'desktop/tauri-plugin-google-drive-auth/target',
];

const targets = includeRust ? [...BUILD_OUTPUT, ...RUST] : BUILD_OUTPUT;

/** Total bytes under a path, following nothing — symlinks count as themselves. */
function sizeOf(target) {
  const stats = statSync(target, { throwIfNoEntry: false });
  if (!stats) return 0;
  if (!stats.isDirectory()) return stats.size;
  let total = 0;
  for (const entry of readdirSync(target, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue; // jniLibs points back into target/
    total += sizeOf(path.join(target, entry.name));
  }
  return total;
}

function human(bytes) {
  const units = ['B', 'KB', 'MB', 'GB'];
  let n = bytes;
  let u = 0;
  while (n >= 1024 && u < units.length - 1) {
    n /= 1024;
    u += 1;
  }
  return `${n < 10 && u > 0 ? n.toFixed(1) : Math.round(n)}${units[u]}`;
}

console.log(
  dryRun
    ? 'Would remove:'
    : `Cleaning build output${includeRust ? ' and Rust targets' : ''} ...`,
);

let freed = 0;
let removed = 0;

for (const rel of targets) {
  const full = path.join(repoRoot, rel);
  if (!existsSync(full)) continue;

  const bytes = sizeOf(full);
  console.log(`  ${human(bytes).padStart(7)}  ${rel}`);
  if (!dryRun) rmSync(full, { recursive: true, force: true });
  freed += bytes;
  removed += 1;
}

if (removed === 0) {
  console.log('  (nothing to remove — already clean)');
} else {
  console.log(
    `\n${dryRun ? 'Would free' : 'Freed'} ${human(freed)} across ${removed} path${removed === 1 ? '' : 's'}.`,
  );
}

if (removed > 0) {
  console.log(
    'Kept: node_modules, the generated Android project (no re-init needed),\n' +
      '  and its un-versioned config — keystore.properties, app/build.gradle.kts.',
  );
  if (!includeRust) {
    console.log('  Rust target dirs kept too; add --all to remove those.');
  }
}
